<?php
// Update language if selected via POST
if (isset($_POST['language'])) {
    $_SESSION['language'] = $_POST['language'];
}

// Default language = English
if (!isset($_SESSION['language'])) {
    $_SESSION['language'] = "en";
}

// Language arrays
$lang = [
    "en" => [
        "site_title" => "Gov Problem Reporter",
        "select_login" => "Select Login",
        "people_login" => "People Login",
        "worker_login" => "Worker Login",
        "admin_login" => "Admin Login",
        "login_register" => "Login / Register",
        "reported_issues" => "Reported Issues",
        "resolved_issues" => "Resolved Issues",
        "in_progress_issues" => "In Progress",
        "report_issue" => "Report an Issue",
        "welcome" => "Welcome",
        "dashboard" => "Dashboard",
        "my_problems" => "My Problems",
        "logout" => "Logout",
        "stats" => "📊 My Problem Stats",
        "total_reported" => "Total Reported",
        "completed" => "Completed",
        "in_progress" => "In Progress",
        "report_new" => "⚠️ Report a New Problem",
        "category" => "Category",
        "description" => "Description",
        "location" => "📍 Problem Location",
        "street" => "Street",
        "area" => "Area",
        "city" => "City",
        "pincode" => "Pincode",
        "upload_photo" => "Upload Photo (optional)",
        "submit" => "🚀 Submit Problem",

        // Profile page keys
        "profile" => "My Profile",
        "personal_details" => "Personal Details",
        "name" => "Name",
        "dob" => "Date of Birth",
        "gender" => "Gender",
        "phone" => "Phone",
        "profile_picture" => "Profile Picture",
        "account_details" => "Account Details",
        "email" => "Email",
        "old_password" => "Old Password",
        "new_password" => "New Password",
        "confirm_password" => "Confirm Password",
        "address" => "Address",
        "door_number" => "Door Number",
        "state" => "State",
        "save" => "Save Changes",
        "select_language" => "Select Language",
        "preferences" => "Preferences / Settings"
    ],

    "te" => [
        "site_title" => "ప్రభుత్వ సమస్య నివేదకుడు",
        "select_login" => "లాగిన్ ఎంచుకోండి",
        "people_login" => "ప్రజల లాగిన్",
        "worker_login" => "కార్మికుల లాగిన్",
        "admin_login" => "అడ్మిన్ లాగిన్",
        "login_register" => "లాగిన్ / రిజిస్టర్",
        "reported_issues" => "నివేదించబడిన సమస్యలు",
        "resolved_issues" => "పరిష్కరించబడినవి",
        "in_progress_issues" => "పనిలో ఉన్నాయి",
        "report_issue" => "సమస్య నివేదించండి",
        "footer" => "© 2025 ప్రభుత్వ సమస్య నివేదకుడు",

        "welcome" => "స్వాగతం",
        "dashboard" => "డాష్‌బోర్డ్",
        "my_problems" => "నా సమస్యలు",
        "logout" => "లాగౌట్",
        "stats" => "📊 నా సమస్యల గణాంకాలు",
        "total_reported" => "మొత్తం నివేదించబడినవి",
        "completed" => "పూర్తి అయినవి",
        "in_progress" => "పనిలో ఉన్నవి",
        "report_new" => "⚠️ కొత్త సమస్యను నివేదించండి",
        "category" => "వర్గం",
        "description" => "వివరణ",
        "location" => "📍 సమస్య ప్రదేశం",
        "street" => "వీధి",
        "area" => "ప్రాంతం",
        "city" => "నగరం",
        "pincode" => "పిన్‌కోడ్",
        "upload_photo" => "ఫోటో అప్‌లోడ్ (ఐచ్చికం)",
        "submit" => "🚀 సమస్యను సమర్పించండి",

        // Profile page keys
        "profile" => "నా ప్రొఫైల్",
        "personal_details" => "వ్యక్తిగత వివరాలు",
        "name" => "పేరు",
        "dob" => "జననం తేది",
        "gender" => "లింగం",
        "phone" => "ఫోన్",
        "profile_picture" => "ప్రొఫైల్ ఫోటో",
        "account_details" => "ఖాతా వివరాలు",
        "email" => "ఇమెయిల్",
        "old_password" => "పాత పాస్వర్డ్",
        "new_password" => "కొత్త పాస్వర్డ్",
        "confirm_password" => "పాస్వర్డ్ ధృవీకరణ",
        "address" => "చిరునామా",
        "door_number" => "ద్వారం సంఖ్య",
        "state" => "రాష్ట్రం",
        "save" => "మార్పులు సేవ్ చేయండి",
        "select_language" => "భాషను ఎంచుకోండి",
        "preferences" => "ప్రాధాన్యతలు / సెట్టింగ్లు"
    ],

    "hn" => [
        "site_title" => "सरकारी समस्या रिपोर्टर",
        "select_login" => "लॉगिन चुनें",
        "people_login" => "लोगिन लोग",
        "worker_login" => "कर्मचारी लॉगिन",
        "admin_login" => "एडमिन लॉगिन",
        "login_register" => "लॉगिन / रजिस्टर",
        "reported_issues" => "रिपोर्ट की गई समस्याएँ",
        "resolved_issues" => "समाधान की गई",
        "in_progress_issues" => "प्रगति में",
        "report_issue" => "समस्या रिपोर्ट करें",
        "footer" => "© 2025 सरकारी समस्या रिपोर्टर",

        "welcome" => "स्वागत है",
        "dashboard" => "डैशबोर्ड",
        "my_problems" => "मेरी समस्याएँ",
        "logout" => "लॉगआउट",
        "stats" => "📊 मेरी समस्या के आँकड़े",
        "total_reported" => "कुल रिपोर्ट",
        "completed" => "पूरा हुआ",
        "in_progress" => "प्रगति पर",
        "report_new" => "⚠️ नई समस्या रिपोर्ट करें",
        "category" => "श्रेणी",
        "description" => "विवरण",
        "location" => "📍 समस्या स्थान",
        "street" => "गली",
        "area" => "क्षेत्र",
        "city" => "शहर",
        "pincode" => "पिनकोड",
        "upload_photo" => "फोटो अपलोड (वैकल्पिक)",
        "submit" => "🚀 समस्या सबमिट करें",

        // Profile page keys
        "profile" => "मेरा प्रोफ़ाइल",
        "personal_details" => "व्यक्तिगत विवरण",
        "name" => "नाम",
        "dob" => "जन्म तिथि",
        "gender" => "लिंग",
        "phone" => "फ़ोन",
        "profile_picture" => "प्रोफ़ाइल तस्वीर",
        "account_details" => "खाता विवरण",
        "email" => "ईमेल",
        "old_password" => "पुराना पासवर्ड",
        "new_password" => "नया पासवर्ड",
        "confirm_password" => "पासवर्ड की पुष्टि",
        "address" => "पता",
        "door_number" => "दरवाज़ा संख्या",
        "state" => "राज्य",
        "save" => "परिवर्तन सहेजें",
        "select_language" => "भाषा चुनें",
        "preferences" => "पसंद / सेटिंग्स"
    ],

    "kn" => [
        "site_title" => "ಸರ್ಕಾರಿ ಸಮಸ್ಯೆ ವರದಿಗಾರ",
        "select_login" => "ಲಾಗಿನ್ ಆಯ್ಕೆಮಾಡಿ",
        "people_login" => "ಜನರ ಲಾಗಿನ್",
        "worker_login" => "ಕಾರ್ಮಿಕ ಲಾಗಿನ್",
        "admin_login" => "ಅಡ್ಮಿನ್ ಲಾಗಿನ್",
        "login_register" => "ಲಾಗಿನ್ / ನೋಂದಣಿ",
        "reported_issues" => "ವರದಿ ಮಾಡಿದ ಸಮಸ್ಯೆಗಳು",
        "resolved_issues" => "ಪರಿಷ್ಕೃತವಾಗಿದೆ",
        "in_progress_issues" => "ಪ್ರಗತಿಯಲ್ಲಿ",
        "report_issue" => "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
        "footer" => "© 2025 ಸರ್ಕಾರಿ ಸಮಸ್ಯೆ ವರದಿಗಾರ",

        "welcome" => "ಸ್ವಾಗತ",
        "dashboard" => "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "my_problems" => "ನನ್ನ ಸಮಸ್ಯೆಗಳು",
        "logout" => "ಲಾಗ್ಔಟ್",
        "stats" => "📊 ನನ್ನ ಸಮಸ್ಯೆಗಳ ಅಂಕಿ ಅಂಶಗಳು",
        "total_reported" => "ಒಟ್ಟು ವರದಿಯಾದವು",
        "completed" => "ಪೂರ್ಣಗೊಂಡಿವೆ",
        "in_progress" => "ನಡೆಯುತ್ತಿದೆ",
        "report_new" => "⚠️ ಹೊಸ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
        "category" => "ವರ್ಗ",
        "description" => "ವಿವರಣೆ",
        "location" => "📍 ಸಮಸ್ಯೆಯ ಸ್ಥಳ",
        "street" => "ರಸ್ತೆ",
        "area" => "ಪ್ರದೇಶ",
        "city" => "ನಗರ",
        "pincode" => "ಪಿನ್‌ಕೋಡ್",
        "upload_photo" => "ಫೋಟೋ ಅಪ್ಲೋಡ್ (ಐಚ್ಛಿಕ)",
        "submit" => "🚀 ಸಮಸ್ಯೆಯನ್ನು ಸಲ್ಲಿಸಿ",

        // Profile page keys
        "profile" => "ನನ್ನ ಪ್ರೊಫೈಲ್",
        "personal_details" => "ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
        "name" => "ಹೆಸರು",
        "dob" => "ಜನ್ಮ ದಿನಾಂಕ",
        "gender" => "ಲಿಂಗ",
        "phone" => "ಫೋನ್",
        "profile_picture" => "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ",
        "account_details" => "ಖಾತೆ ವಿವರಗಳು",
        "email" => "ಇಮೇಲ್",
        "old_password" => "ಹಳೆಯ ಪಾಸ್‌ವರ್ಡ್",
        "new_password" => "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
        "confirm_password" => "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಣ",
        "address" => "ವಿಳಾಸ",
        "door_number" => "ದ್ವಾರ ಸಂಖ್ಯೆ",
        "state" => "ರಾಜ್ಯ",
        "save" => "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
        "select_language" => "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "preferences" => "ಆಗ್ಯತೆ / ಸೆಟ್ಟಿಂಗ್ಗಳು"
    ]
];
$lang['en']['select_location'] = "Select Location on Map";
$lang['te']['select_location'] = "నక్షత్రంలో స్థానం ఎంచుకోండి";
$lang['hn']['select_location'] = "मानचित्र पर स्थान चुनें";
$lang['kn']['select_location'] = "ಮ್ಯಾಪ್‌ನಲ್ಲಿ ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ";
// Use this variable on pages
$selectedLang = $_SESSION['language'];
?>