<?php
// lang.php - Master Multilingual Translation Dictionary

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (isset($_POST['language'])) {
    $_SESSION['language'] = $_POST['language'];
}

$lang = [
    "en" => [
        "site_title" => "CivicConnect",
        "portal_tagline" => "Smart City Portal",
        "select_login" => "Portal Access & Login",
        "people_login" => "Citizen Portal",
        "worker_login" => "Field Officer Portal",
        "admin_login" => "Admin Dashboard",
        "login_register" => "Select Portal",
        "welcome" => "Welcome",
        "dashboard" => "Dashboard",
        "my_problems" => "My Problems",
        "profile" => "My Profile",
        "logout" => "Logout",
        "change_role" => "Change Role",
        "back_to_home" => "Back to Main Home",
        
        "role_selection_title" => "Select Your Portal to Get Started",
        "role_selection_desc" => "Empowering citizens, municipal field workers, and department administrators to resolve civic issues faster with Vision AI intelligence.",
        "citizen_desc" => "Report civic problems like potholes or garbage with instant AI photo recognition and real-time status tracking.",
        "worker_desc" => "View assigned ward complaints, submit before & after resolution photo evidence, and update task progress.",
        "admin_desc" => "Manage municipal staff, allocate complaints based on AI severity ratings, and audit resolved issues.",
        "login_as_citizen" => "Login as Citizen",
        "login_as_worker" => "Login as Officer",
        "login_as_admin" => "Login as Admin",
        
        "citizen_welcome" => "Welcome back! Sign in to report and track issues.",
        "worker_welcome" => "Sign in to view assigned ward tasks and submit resolution proof.",
        "admin_welcome" => "Sign in to manage municipal staff, complaint allocation, and city analytics.",
        "dont_have_account" => "Don't have a citizen account?",
        "create_account" => "Create Account",

        "hero_pill" => "Powered by Multimodal Vision AI & GIS Maps",
        "hero_title" => "Bridging Citizens & Municipal Authorities Together",
        "hero_subtitle" => "Report public issues like potholes, garbage accumulation, or streetlights in seconds. Instant Vision AI scanning auto-detects problem categories and tracks resolution end-to-end.",
        "report_issue" => "Report an Issue Now",
        "portal_access" => "Portal Access & Login",
        "reported_issues" => "Reported Issues",
        "in_progress_issues" => "In Progress",
        "resolved_issues" => "Resolved Issues",
        "ai_scanned_issues" => "AI Risk Scanned",
        
        "report_new" => "⚠️ Report a New Problem",
        "category" => "Category",
        "description" => "Description",
        "location" => "📍 Problem Location",
        "select_location" => "Select Location on Map (Click Pin)",
        "street" => "Street",
        "area" => "Area",
        "city" => "City",
        "pincode" => "Pincode",
        "upload_photo" => "Upload Photo (Optional)",
        "submit" => "🚀 Submit Problem",
        "duplicate_report" => "This problem is already reported within 45 meters radius!!",
        
        "personal_details" => "Personal Details",
        "name" => "Name",
        "dob" => "Date of Birth",
        "gender" => "Gender",
        "phone" => "Phone",
        "profile_picture" => "Profile Picture",
        "account_details" => "Account Details",
        "email" => "Email Address",
        "old_password" => "Old Password",
        "new_password" => "New Password",
        "confirm_password" => "Confirm Password",
        "address" => "Address",
        "door_number" => "Door Number",
        "state" => "State",
        "save" => "Save Changes",
        "select_language" => "Select Language",
        "preferences" => "Preferences / Settings",
        
        "features_title" => "Built for Modern Smart Cities",
        "features_subtitle" => "Combining cutting-edge AI, location pinning, and multi-language support for seamless civic management.",
        "feature1_title" => "Vision AI Auto-Scan",
        "feature1_desc" => "Upload a photo of a pothole or garbage dump, and AI Vision instantly auto-selects the category and assigns a risk severity rating.",
        "feature2_title" => "GIS Pinning & Haversine Math",
        "feature2_desc" => "Drop an exact location pin using OpenStreetMap. Built-in Haversine geodesic math prevents duplicate reports within 45 meters.",
        "feature3_title" => "AI Dynamic Translation",
        "feature3_desc" => "Citizens can write in Telugu, Hindi, Kannada, or English. Field workers use 1-click AI translation to view complaints in their preferred language.",
        "workflow_title" => "How CivicConnect Works",
        "workflow_subtitle" => "Simple, transparent, and verified from report to resolution.",
        "step1_title" => "Upload Photo",
        "step1_desc" => "Citizen captures problem photo on mobile/desktop.",
        "step2_title" => "AI Auto-Scan",
        "step2_desc" => "AI categorizes issue & sets severity risk rating.",
        "step3_title" => "Officer Dispatched",
        "step3_desc" => "Admin assigns ward officer to resolve the task.",
        "step4_title" => "Verified Resolution",
        "step4_desc" => "Worker submits Before/After proof photo to close ticket.",
        "community_reports_title" => "Recent Community Reports",
        "community_reports_subtitle" => "Real issues being tracked and resolved across municipal wards.",
        "footer" => "© 2026 CivicConnect Platform | Powered by Vision AI & OpenStreetMap"
    ],

    "te" => [
        "site_title" => "సివిక్ కనెక్ట్",
        "portal_tagline" => "స్మార్ట్ సిటీ పోర్టల్",
        "select_login" => "పోర్టల్ ప్రవేశం & లాగిన్",
        "people_login" => "ప్రజల పోర్టల్",
        "worker_login" => "ఫీల్డ్ ఆఫీసర్ పోర్టల్",
        "admin_login" => "అడ్మిన్ డాష్‌బోర్డ్",
        "login_register" => "పోర్టల్ ఎంచుకోండి",
        "welcome" => "స్వాగతం",
        "dashboard" => "డాష్‌బోర్డ్",
        "my_problems" => "నా సమస్యలు",
        "profile" => "నా ప్రొఫైల్",
        "logout" => "లాగౌట్",
        "change_role" => "రోల్ మార్చండి",
        "back_to_home" => "ముఖ్య పేజీకి తిరిగి వెళ్లండి",
        
        "role_selection_title" => "ప్రారంభించడానికి మీ పోర్టల్‌ను ఎంచుకోండి",
        "role_selection_desc" => "విజన్ AI సాంకేతికతతో ప్రజలు, ఫీల్డ్ అధికారులు మరియు అడ్మిన్లు సమస్యలను త్వరగా పరిష్కరించడానికి సహాయపడుతుంది.",
        "citizen_desc" => "రోడ్డు గుంతలు లేదా చెత్త సమస్యలను AI ఫోటో గుర్తింపు మరియు ప్రత్యక్ష ట్రాకింగ్‌తో నివేదించండి.",
        "worker_desc" => "కేటాయించిన వార్డు ఫిర్యాదులను చూడండి, పరిష్కార ఫోటో సాక్ష్యాలను సమర్పించండి.",
        "admin_desc" => "పురపాలక సిబ్బందిని నిర్వహించండి, AI తీవ్రత ఆధారంగా పనులను కేటాయించండి.",
        "login_as_citizen" => "పౌరుడిగా లాగిన్ అవ్వండి",
        "login_as_worker" => "అధికారిగా లాగిన్ అవ్వండి",
        "login_as_admin" => "అడ్మిన్‌గా లాగిన్ అవ్వండి",
        
        "citizen_welcome" => "తిరిగి స్వాగతం! సమస్యలను నివేదించడానికి సైన్ ఇన్ చేయండి.",
        "worker_welcome" => "కేటాయించిన పనులను చూడటానికి ఆఫీసర్ లాగిన్ అవ్వండి.",
        "admin_welcome" => "సిబ్బంది మరియు పనుల నిర్వహణకు అడ్మిన్ లాగిన్ అవ్వండి.",
        "dont_have_account" => "ఖాతా లేదా?",
        "create_account" => "ఖాతా తెరవండి",
        
        "hero_pill" => "విజన్ AI & GIS మ్యాప్‌లతో పనిచేస్తుంది",
        "hero_title" => "ప్రజలను మరియు పురపాలక అధికారులను ఒకటిగా జోడించడం",
        "hero_subtitle" => "రోడ్డు గుంతలు, చెత్త సమస్యలు లేదా వీధి దీపాల సమస్యలను సెకన్లలో నివేదించండి. AI విజన్ సమస్య రకాన్ని మరియు తీవ్రతను ఆటోమేటిక్‌గా గుర్తిస్తుంది.",
        "report_issue" => "ఇప్పుడే సమస్యను నివేదించండి",
        "portal_access" => "పోర్టల్ ప్రవేశం & లాగిన్",
        "reported_issues" => "నివేదించబడిన సమస్యలు",
        "in_progress_issues" => "పనిలో ఉన్నవి",
        "resolved_issues" => "పరిష్కరించబడినవి",
        "ai_scanned_issues" => "AI తనిఖీ చేసినవి",
        
        "report_new" => "⚠️ కొత్త సమస్యను నివేదించండి",
        "category" => "సమస్య వర్గం",
        "description" => "సమస్య వివరణ",
        "location" => "📍 సమస్య స్థానం",
        "select_location" => "మ్యాప్‌లో స్థానాన్ని ఎంచుకోండి (పిన్ పై క్లిక్ చేయండి)",
        "street" => "వీధి",
        "area" => "ప్రాంతం",
        "city" => "నగరం",
        "pincode" => "పిన్‌కోడ్",
        "upload_photo" => "ఫోటో అప్‌లోడ్ (ఐచ్ఛికం)",
        "submit" => "🚀 సమస్యను సమర్పించండి",
        "duplicate_report" => "ఈ సమస్య ఇప్పటికే 45 మీటర్ల పరిధిలో నివేదించబడింది!!",
        
        "personal_details" => "వ్యక్తిగత వివరాలు",
        "name" => "పేరు",
        "dob" => "జన్మ తేదీ",
        "gender" => "లింగం",
        "phone" => "ఫోన్ నంబర్",
        "profile_picture" => "ప్రొఫైల్ ఫోటో",
        "account_details" => "ఖాతా వివరాలు",
        "email" => "ఇమెయిల్ చిరునామా",
        "old_password" => "పాత పాస్‌వర్డ్",
        "new_password" => "కొత్త పాస్‌వర్డ్",
        "confirm_password" => "పాస్‌వర్డ్ ధృవీకరణ",
        "address" => "చిరునామా",
        "door_number" => "ఇంటి సంఖ్య",
        "state" => "రాష్ట్రం",
        "save" => "మార్పులను సేవ్ చేయండి",
        "select_language" => "భాషను ఎంచుకోండి",
        "preferences" => "ప్రాధాన్యతలు / సెట్టింగ్‌లు",
        
        "features_title" => "ఆధునిక స్మార్ట్ నగరాల కోసం నిర్మించబడింది",
        "features_subtitle" => "అత్యాధునిక AI, ఖచ్చితమైన స్థాన మ్యాపింగ్ మరియు బహుభాషా మద్దతుతో పౌర సేవల నిర్వహణ.",
        "feature1_title" => "విజన్ AI ఆటో స్కానింగ్",
        "feature1_desc" => "సమస్య ఫోటో అప్‌లోడ్ చేయగానే, AI విజన్ సమస్య వర్గాన్ని మరియు ప్రమాద తీవ్రతను తక్షణమే గుర్తిస్తుంది.",
        "feature2_title" => "GIS స్థాన పిన్నింగ్ & డూప్లికేట్ నిరోధకం",
        "feature2_desc" => "ఓపెన్ స్ట్రీట్ మ్యాప్‌ ద్వారా ఖచ్చితమైన స్థానాన్ని పిన్ చేయండి. 45 మీటర్ల పరిధిలోని డూప్లికేట్ నివేదికలను AI నిరోధిస్తుంది.",
        "feature3_title" => "AI ప్రత్యక్ష భాషా అనువాదం",
        "feature3_desc" => "ప్రజలు తెలుగు, హిందీ, కన్నడ లేదా ఇంగ్లీషులో రాయవచ్చు. అధికారులు 1-క్లిక్ AI అనువాదంతో తమ భాషలో చదవవచ్చు.",
        "workflow_title" => "సివిక్ కనెక్ట్ ఎలా పనిచేస్తుంది",
        "workflow_subtitle" => "నివేదిక నుండి పరిష్కారం వరకు సరళమైనది మరియు పారదర్శకమైనది.",
        "step1_title" => "ఫోటో అప్‌లోడ్ చేయండి",
        "step1_desc" => "మొబైల్ లేదా డెస్క్‌టాప్ నుండి సమస్య ఫోటో తీయండి.",
        "step2_title" => "AI ఆటో స్కానింగ్",
        "step2_desc" => "AI వర్గాన్ని మరియు ప్రమాద తీవ్రతను నిర్ణయిస్తుంది.",
        "step3_title" => "అధికారి నియామకం",
        "step3_desc" => "అడ్మిన్ సంబంధిత వార్డు అధికారికి పనిని కేటాయిస్తారు.",
        "step4_title" => "ధృవీకరించబడిన పరిష్కారం",
        "step4_desc" => "పని పూర్తయిన తర్వాత అధికారి ఫోటో ఆధారాలు సమర్పిస్తారు.",
        "community_reports_title" => "ఇటీవలి నివేదికలు",
        "community_reports_subtitle" => "పురపాలక వార్డులలో పరిష్కరించబడుతున్న వాస్తవ సమస్యలు.",
        "footer" => "© 2026 సివిక్ కనెక్ట్ | విజన్ AI & ఓపెన్ స్ట్రీట్ మ్యాప్‌తో పనిచేస్తుంది"
    ],

    "hn" => [
        "site_title" => "सिविक कनेक्ट",
        "portal_tagline" => "स्मार्ट सिटी पोर्टल",
        "select_login" => "पोर्टल लॉगिन",
        "people_login" => "नागरिक पोर्टल",
        "worker_login" => "फील्ड ऑफिसर पोर्टल",
        "admin_login" => "एडमिन डैशबोर्ड",
        "login_register" => "पोर्टल चुनें",
        "welcome" => "स्वागत है",
        "dashboard" => "डैशबोर्ड",
        "my_problems" => "मेरी शिकायतें",
        "profile" => "मेरा प्रोफ़ाइल",
        "logout" => "लॉगआउट",
        "change_role" => "रोल बदलें",
        "back_to_home" => "मुख्य पृष्ठ पर वापस जाएं",
        
        "role_selection_title" => "शुरू करने के लिए अपना पोर्टल चुनें",
        "role_selection_desc" => "नागरिकों, नगर निगम कर्मचारियों और अधिकारियों को समस्याओं को तेज़ी से हल करने में सक्षम बनाना।",
        "citizen_desc" => "गड्ढे या कचरे जैसी समस्याओं को AI फोटो पहचान के साथ रिपोर्ट करें।",
        "worker_desc" => "सौंपी गई शिकायतें देखें, समाधान की फोटो जमा करें।",
        "admin_desc" => "कर्मचारियों का प्रबंधन करें, AI गंभीरता के आधार पर काम आवंटित करें।",
        "login_as_citizen" => "नागरिक के रूप में लॉगिन करें",
        "login_as_worker" => "अधिकारी के रूप में लॉगिन करें",
        "login_as_admin" => "एडमिन के रूप में लॉगिन करें",
        
        "citizen_welcome" => "वापसी पर स्वागत है! रिपोर्ट करने के लिए साइन इन करें।",
        "worker_welcome" => "सौंपे गए कार्यों को देखने के लिए साइन इन करें।",
        "admin_welcome" => "प्रबंधन के लिए एडमिन साइन इन करें।",
        "dont_have_account" => "खाता नहीं है?",
        "create_account" => "खाता बनाएं",

        "hero_pill" => "विज़न AI और GIS मैप्स द्वारा संचालित",
        "hero_title" => "नागरिकों और नगर निगम अधिकारियों को जोड़ना",
        "hero_subtitle" => "सड़क के गड्ढे, कचरा या स्ट्रीट लाइट की समस्याओं को सेकंडों में रिपोर्ट करें। AI विज़न स्वचालित रूप से श्रेणी और गंभीरता की पहचान करता है।",
        "report_issue" => "अभी समस्या रिपोर्ट करें",
        "portal_access" => "पोर्टल प्रवेश और लॉगिन",
        "reported_issues" => "कुल दर्ज शिकायतें",
        "in_progress_issues" => "प्रगति पर समस्याएं",
        "resolved_issues" => "हल की गई समस्याएं",
        "ai_scanned_issues" => "AI द्वारा जांच की गई",
        
        "report_new" => "⚠️ नई समस्या रिपोर्ट करें",
        "category" => "समस्या श्रेणी",
        "description" => "समस्या का विवरण",
        "location" => "📍 समस्या स्थान",
        "select_location" => "मानचित्र पर स्थान चुनें (पिन पर क्लिक करें)",
        "street" => "सड़क / गली",
        "area" => "क्षेत्र",
        "city" => "शहर",
        "pincode" => "पिनकोड",
        "upload_photo" => "फोटो अपलोड (वैकल्पिक)",
        "submit" => "🚀 समस्या सबमिट करें",
        "duplicate_report" => "यह समस्या 45 मीटर के भीतर पहले ही दर्ज की जा चुकी है!!",
        
        "personal_details" => "व्यक्तिगत विवरण",
        "name" => "नाम",
        "dob" => "जन्म तिथि",
        "gender" => "लिंग",
        "phone" => "फ़ोन नंबर",
        "profile_picture" => "प्रोफ़ाइल फोटो",
        "account_details" => "खाता विवरण",
        "email" => "ईमेल पता",
        "old_password" => "पुराना पासवर्ड",
        "new_password" => "नया पासवर्ड",
        "confirm_password" => "पासवर्ड की पुष्टि",
        "address" => "पता",
        "door_number" => "मकान नंबर",
        "state" => "राज्य",
        "save" => "परिवर्तन सहेजें",
        "select_language" => "भाषा चुनें",
        "preferences" => "पसंद / सेटिंग्स",
        
        "features_title" => "आधुनिक स्मार्ट शहरों के लिए निर्मित",
        "features_subtitle" => "उन्नत AI, सटीक स्थान मैपिंग और बहुभाषी सहायता का संयोजन।",
        "feature1_title" => "विज़न AI ऑटो स्कैन",
        "feature1_desc" => "फोटो अपलोड करते ही AI विज़न स्वचालित रूप से श्रेणी और जोखिम गंभीरता रेटिंग तय करता है।",
        "feature2_title" => "GIS लोकेशन मैपिंग",
        "feature2_desc" => "ओपनस्ट्रीटमैप पर सटीक स्थान पिन करें। 45 मीटर के भीतर डुप्लिकेट रिपोर्ट रोकी जाती हैं।",
        "feature3_title" => "AI लाइव भाषा अनुवादक",
        "feature3_desc" => "नागरिक हिंदी, तेलुगु, कन्नड़ या अंग्रेजी में लिख सकते हैं। अधिकारी 1-क्लिक AI अनुवाद से पढ़ सकते हैं।",
        "workflow_title" => "सिविक कनेक्ट कैसे काम करता है",
        "workflow_subtitle" => "रिपोर्ट से लेकर समाधान तक सरल और पारदर्शी।",
        "step1_title" => "फोटो अपलोड करें",
        "step1_desc" => "नागरिक समस्या की फोटो खींचते हैं।",
        "step2_title" => "AI ऑटो स्कैन",
        "step2_desc" => "AI श्रेणी और जोखिम रेटिंग तय करता है।",
        "step3_title" => "अधिकारी की नियुक्ति",
        "step3_desc" => "एडमिन कार्य के लिए संबंधित अधिकारी नियुक्त करता है।",
        "step4_title" => "सत्यापित समाधान",
        "step4_desc" => "कार्य पूरा होने पर अधिकारी फोटो प्रमाण जमा करता है।",
        "community_reports_title" => "हालिया रिपोर्ट",
        "community_reports_subtitle" => "वार्डों में ट्रैक और हल की जा रही वास्तविक समस्याएं।",
        "footer" => "© 2026 सिविक कनेक्ट | विज़न AI और ओपनस्ट्रीटमैप द्वारा संचालित"
    ],

    "kn" => [
        "site_title" => "ಸಿವಿಕ್ ಕನೆಕ್ಟ್",
        "portal_tagline" => "ಸ್ಮಾರ್ಟ್ ಸಿಟಿ ಪೋರ್ಟಲ್",
        "select_login" => "ಪೋರ್ಟಲ್ ಲಾಗಿನ್",
        "people_login" => "ನಾಗರಿಕ ಪೋರ್ಟಲ್",
        "worker_login" => "ಕ್ಷೇತ್ರಾಧಿಕಾರಿ ಪೋರ್ಟಲ್",
        "admin_login" => "ಆಡಳಿತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "login_register" => "ಪೋರ್ಟಲ್ ಆಯ್ಕೆಮಾಡಿ",
        "welcome" => "ಸ್ವಾಗತ",
        "dashboard" => "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "my_problems" => "ನನ್ನ ದೂರುಗಳು",
        "profile" => "ನನ್ನ ಪ್ರೊಫೈಲ್",
        "logout" => "ಲಾಗ್ಔಟ್",
        "change_role" => "ಪಾತ್ರ ಬದಲಾಯಿಸಿ",
        "back_to_home" => "ಮುಖ್ಯ ಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
        
        "role_selection_title" => "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಪೋರ್ಟಲ್ ಆಯ್ಕೆಮಾಡಿ",
        "role_selection_desc" => "ನಾಗರಿಕರು, ಕ್ಷೇತ್ರಾಧಿಕಾರಿಗಳು ಮತ್ತು ಆಡಳಿತಾಧಿಕಾರಿಗಳು ಸಮಸ್ಯೆಗಳನ್ನು ಶೀಘ್ರವಾಗಿ ಪರಿಹರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
        "citizen_desc" => "ರಸ್ತೆ ಗುಂಡಿ ಅಥವಾ ಕಸದ ಸಮಸ್ಯೆಗಳನ್ನು AI ಫೋಟೋ ತಪಾಸಣೆಯೊಂದಿಗೆ ವರದಿ ಮಾಡಿ.",
        "worker_desc" => "ನಿಯೋಜಿತ ದೂರುಗಳನ್ನು ವೀಕ್ಷಿಸಿ, ಪರಿಹಾರದ ಫೋಟೋ ಸಾಕ್ಷಿ ಸಲ್ಲಿಸಿ.",
        "admin_desc" => "ಸಿಬ್ಬಂದಿ ನಿರ್ವಹಿಸಿ, AI ತೀವ್ರತೆಯ ಆಧಾರದ ಮೇಲೆ ಕೆಲಸ ನಿಯೋಜಿಸಿ.",
        "login_as_citizen" => "ನಾಗರಿಕರಾಗಿ ಲಾಗಿನ್ ಆಗಿ",
        "login_as_worker" => "ಅಧಿಕಾರಿಯಾಗಿ ಲಾಗಿನ್ ಆಗಿ",
        "login_as_admin" => "ಅಡ್ಮಿನ್ ಆಗಿ ಲಾಗಿನ್ ಆಗಿ",
        
        "citizen_welcome" => "ಮರಳಿ ಸ್ವಾಗತ! ಸೈನ್ ಇನ್ ಮಾಡಿ.",
        "worker_welcome" => "ಕೆಲಸಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
        "admin_welcome" => "ಆಡಳಿತಕ್ಕಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
        "dont_have_account" => "ಖಾತೆ ಇಲ್ಲವೇ?",
        "create_account" => "ಖಾತೆ ತೆರೆಯಿರಿ",

        "hero_pill" => "ವಿಷನ್ AI ಮತ್ತು GIS ನಕ್ಷೆಗಳಿಂದ ಚಾಲಿತವಾಗಿದೆ",
        "hero_title" => "ನಾಗರಿಕರು ಮತ್ತು ಪೌರಾಡಳಿತ ಅಧಿಕಾರಿಗಳನ್ನು ಬೆಸೆಯುವುದು",
        "hero_subtitle" => "ರಸ್ತೆ ಗುಂಡಿ, ಕಸ ಅಥವಾ ಬೀದಿ ದೀಪದ ಸಮಸ್ಯೆಗಳನ್ನು ಕ್ಷಣಾರ್ಧದಲ್ಲಿ ವರದಿ ಮಾಡಿ. AI ವಿಷನ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ತೀವ್ರತೆಯನ್ನು ಗುರುತಿಸುತ್ತದೆ.",
        "report_issue" => "ಈಗಲೇ ದೂರು ಸಲ್ಲಿಸಿ",
        "portal_access" => "ಪೋರ್ಟಲ್ ಪ್ರವೇಶ & ಲಾಗಿನ್",
        "reported_issues" => "ದಾಖಲಾದ ದೂರುಗಳು",
        "in_progress_issues" => "ಪ್ರಗತಿಯಲ್ಲಿರುವವು",
        "resolved_issues" => "ಪರಿಹರಿಸಲಾದವು",
        "ai_scanned_issues" => "AI ತಪಾಸಣೆ ಮಾಡಿದ್ದು",
        
        "report_new" => "⚠️ ಹೊಸ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
        "category" => "ಸಮಸ್ಯೆಯ ವರ್ಗ",
        "description" => "ಸಮಸ್ಯೆಯ ವಿವರಣೆ",
        "location" => "📍 ಸಮಸ್ಯೆಯ ಸ್ಥಳ",
        "select_location" => "ಮ್ಯಾಪ್‌ನಲ್ಲಿ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ (ಪಿನ್ ಕ್ಲಿಕ್ ಮಾಡಿ)",
        "street" => "ರಸ್ತೆ / ಬೀದಿ",
        "area" => "ಪ್ರದೇಶ",
        "city" => "ನಗರ",
        "pincode" => "ಪಿನ್‌ಕೋಡ್",
        "upload_photo" => "ಫೋಟೋ ಅಪ್ಲೋಡ್ (ಐಚ್ಛಿಕ)",
        "submit" => "🚀 ಸಮಸ್ಯೆಯನ್ನು ಸಲ್ಲಿಸಿ",
        "duplicate_report" => "ಈ ಸಮಸ್ಯೆಯು 45 ಮೀಟರ್ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಈಗಾಗಲೇ ವರದಿಯಾಗಿದೆ!!",
        
        "personal_details" => "ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
        "name" => "ಹೆಸರು",
        "dob" => "ಜನ್ಮ ದಿನಾಂಕ",
        "gender" => "ಲಿಂಗ",
        "phone" => "ಫೋನ್ ಸಂಖ್ಯೆ",
        "profile_picture" => "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ",
        "account_details" => "ಖಾತೆ ವಿವರಗಳು",
        "email" => "ಇಮೇಲ್ ವಿಳಾಸ",
        "old_password" => "ಹಳೆಯ ಪಾಸ್‌ವರ್ಡ್",
        "new_password" => "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
        "confirm_password" => "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಣ",
        "address" => "ವಿಳಾಸ",
        "door_number" => "ಮನೆ ಸಂಖ್ಯೆ",
        "state" => "ರಾಜ್ಯ",
        "save" => "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
        "select_language" => "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "preferences" => "ಆದ್ಯತೆಗಳು / ಸೆಟ್ಟಿಂಗ್ಗಳು",
        
        "features_title" => "ಆಧುನಿಕ ಸ್ಮಾರ್ಟ್ ನಗರಗಳಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ",
        "features_subtitle" => "ಸುಧಾರಿತ AI, ನಿಖರ ಸ್ಥಳ ನಕ್ಷೆ ಮತ್ತು ಬಹುಭಾಷಾ ಬೆಂಬಲದೊಂದಿಗೆ ಪೌರ ಸೇವೆಗಳ ನಿರ್ವಹಣೆ.",
        "feature1_title" => "ವಿಷನ್ AI ಆಟೋ ಸ್ಕ್ಯಾನ್",
        "feature1_desc" => "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ತಕ್ಷಣ AI ವಿಷನ್ ಸಮಸ್ಯೆಯ ವರ್ಗ ಮತ್ತು ತೀವ್ರತೆಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ನಿರ್ಧರಿಸುತ್ತದೆ.",
        "feature2_title" => "GIS ಸ್ಥಳ ಪಿನ್ನಿಂಗ್",
        "feature2_desc" => "ಓಪನ್‌ಸ್ಟ್ರೀಟ್‌ಮ್ಯಾಪ್‌ನಲ್ಲಿ ನಿಖರ ಸ್ಥಳವನ್ನು ಪಿನ್ ಮಾಡಿ. 45 ಮೀಟರ್ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ನಕಲಿ ವರದಿಗಳನ್ನು ತಡೆಯಲಾಗುತ್ತದೆ.",
        "feature3_title" => "AI ಲೈವ್ ಭಾಷಾ ಅನುವಾದಕ",
        "feature3_desc" => "ನಾಗರಿಕರು ಕನ್ನಡ, ತೆಲುಗು, ಹಿಂದಿ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಬರೆಯಬಹುದು. ಅಧಿಕಾರಿಗಳು 1-ಕ್ಲಿಕ್ AI ಅನುವಾದದ ಮೂಲಕ ಓದಬಹುದು.",
        "workflow_title" => "ಸಿವಿಕ್ ಕನೆಕ್ಟ್ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
        "workflow_subtitle" => "ವರದಿಯಿಂದ ಪರಿಹಾರದವರೆಗೆ ಸರಳ ಮತ್ತು ಪಾರದರ್ಶಕ.",
        "step1_title" => "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        "step1_desc" => "ನಾಗರಿಕರು ಸಮಸ್ಯೆಯ ಫೋಟೋ ತೆಗೆಯುತ್ತಾರೆ.",
        "step2_title" => "AI ಆಟೋ ಸ್ಕ್ಯಾನ್",
        "step2_desc" => "AI ತೀವ್ರತೆಯನ್ನು ನಿರ್ಧರಿಸುತ್ತದೆ.",
        "step3_title" => "ಅಧಿಕಾರಿ ನೇಮಕ",
        "step3_desc" => "ಆಡಳಿತಾಧಿಕಾರಿ ಕೆಲಸಕ್ಕೆ ಅಧಿಕಾರಿಯನ್ನು ನೇಮಿಸುತ್ತಾರೆ.",
        "step4_title" => "ದೃಢೀಕರಿಸಿದ ಪರಿಹಾರ",
        "step4_desc" => "ಕೆಲಸ ಮುಗಿದ ನಂತರ ಅಧಿಕಾರಿ ಫೋಟೋ ಸಾಕ್ಷಿ ಸಲ್ಲಿಸುತ್ತಾರೆ.",
        "community_reports_title" => "ಇತ್ತೀಚಿನ ವರದಿಗಳು",
        "community_reports_subtitle" => "ವಾರ್ಡ್‌ಗಳಲ್ಲಿ ಪರಿಹರಿಸಲಾಗುತ್ತಿರುವ ವಾಸ್ತವಿಕ ದೂರುಗಳು.",
        "footer" => "© 2026 ಸಿವಿಕ್ ಕನೆಕ್ಟ್ | ವಿಷನ್ AI ಮತ್ತು ಓಪನ್‌ಸ್ಟ್ರೀಟ್‌ಮ್ಯಾಪ್‌ನಿಂದ ಚಾಲಿತ"
    ]
];

$selectedLang = $_SESSION['language'] ?? 'en';
if (!isset($lang[$selectedLang])) {
    $selectedLang = 'en';
}
